adminUser:
  password: vault:rom-cjxd-11-3/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: rverduci@cloudbees.com
  token: vault:rom-cjxd-11-3/pipelineUser:token
  username: core-platform-test-bot
prow:
  hmacToken: vault:rom-cjxd-11-3/prow:hmacToken
